# Generated by Django 4.1.3 on 2023-06-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='login',
            new_name='username',
        ),
    ]
