# Generated by Django 4.1.3 on 2023-06-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_utilisateur_last_login_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
