# Generated by Django 4.1.3 on 2023-06-27 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateur', '0010_utilisateur_last_login_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilUtilisateur',
            new_name='UserProfile',
        ),
    ]
