# Generated by Django 4.1.3 on 2023-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_rename_profilutilisateur_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_user',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
