# Generated by Django 4.1.3 on 2023-06-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0012_userprofile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profil',
            field=models.CharField(max_length=50),
        ),
    ]
