# Generated by Django 4.1.3 on 2023-06-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0013_alter_userprofile_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_user',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
