# Generated by Django 4.1.3 on 2023-06-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0014_remove_userprofile_id_alter_userprofile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
