# Generated by Django 4.1.3 on 2023-06-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0015_alter_userprofile_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_user',
            new_name='idUser',
        ),
    ]
