# Generated by Django 4.1.3 on 2023-07-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0018_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='idUser',
            new_name='id',
        ),
    ]
