# Generated by Django 3.1.14 on 2023-10-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0022_auto_20230815_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
