# Generated by Django 3.1.14 on 2023-10-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0023_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('application_mode', models.IntegerField()),
                ('displaced', models.BooleanField(default=False)),
                ('debtor', models.BooleanField(default=False)),
                ('tuition_fees_up_to_date', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=10)),
                ('scholarship_holder', models.BooleanField(default=False)),
                ('age_at_enrollment', models.IntegerField()),
                ('curricular_units_1st_sem_enrolled', models.IntegerField()),
                ('curricular_units_1st_sem_approved', models.IntegerField()),
                ('curricular_units_1st_sem_grade', models.FloatField()),
                ('curricular_units_2nd_sem_enrolled', models.IntegerField()),
                ('curricular_units_2nd_sem_approved', models.IntegerField()),
                ('curricular_units_2nd_sem_grade', models.FloatField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.classe')),
            ],
        ),
    ]
