# Generated by Django 3.1.14 on 2023-10-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0024_classe_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='proba_reussite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='risque_abandon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
