# Generated by Django 4.1.3 on 2022-12-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compagnie",
            name="logo",
            field=models.ImageField(blank=True, upload_to="photo/%Y/%m/%d"),
        ),
    ]
